const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const data=window.COURSE_DATA, KEY='iafarmacia.v31';
const state=JSON.parse(localStorage.getItem(KEY)||'{"doneModules":[],"doneCases":[],"fav":[],"theme":"light","teacherNotes":{},"slide":0,"deck":"all"}');
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderProgress();}
function init(){document.documentElement.dataset.theme=state.theme; renderNav(); bindGlobal(); route();}
function bindGlobal(){document.addEventListener('click',e=>{const t=e.target.closest('[data-action]'); if(!t)return; const a=t.dataset.action,id=t.dataset.id; if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save()} if(a==='done-module'){toggle(state.doneModules,id);save();route()} if(a==='done-case'){toggle(state.doneCases,id);save();route()} if(a==='fav'){toggle(state.fav,id);save();route()} if(a==='reset'&&confirm('¿Reiniciar progreso local?')){localStorage.removeItem(KEY);location.reload()} if(a==='certificate')downloadCertificate(); if(a==='print')window.print(); if(a==='download-guide')downloadGuide(); if(a==='random-question')randomQuestion(); if(a==='timer')startTimer(+t.dataset.minutes||10); if(a==='notes-save')saveNotes(t.dataset.module); if(a==='set-deck'){state.deck=id;state.slide=0;save();location.hash='presentacion'} if(a==='slides-reset'){state.slide=0;save();renderPresentation()} if(a==='slide-next')moveSlide(1); if(a==='slide-prev')moveSlide(-1); if(a==='fullscreen')document.documentElement.requestFullscreen?.();}); window.addEventListener('hashchange',route); document.addEventListener('keydown',e=>{if(!location.hash.startsWith('#presentacion'))return; if(['ArrowRight',' '].includes(e.key)){e.preventDefault();moveSlide(1)} if(e.key==='ArrowLeft'){e.preventDefault();moveSlide(-1)} if(e.key==='Escape'){location.hash='inicio'}});}
function toggle(arr,id){const i=arr.indexOf(id); i>-1?arr.splice(i,1):arr.push(id)}
function renderNav(){ $('#app-nav').innerHTML=`<a href="#inicio">Inicio</a><a href="#catalogo">Módulos</a><a href="#casos">Casos</a><a href="#presentacion">Presentación</a><a href="#docente">Modo docente</a><a href="#acerca">Acerca</a><a href="#historial">Historial</a><a href="#recursos">Recursos</a><button data-action="theme">Claro/oscuro</button>`; renderProgress();}
function renderProgress(){const n=data.modules.length,c=data.cases.length; $('#progressText').textContent=`${state.doneModules.length}/${n} módulos · ${state.doneCases.length}/${c} casos completados`; $('#progressBar').style.width=Math.round((state.doneModules.length+state.doneCases.length)/(n+c)*100)+'%';}
function route(){const h=location.hash.replace('#','')||'inicio'; const m=data.modules.find(x=>x.id===h); const c=data.cases.find(x=>x.id===h); if(m)return renderModule(m); if(c)return renderCase(c); if(h==='catalogo')return renderCatalog(); if(h==='casos')return renderCases(); if(h==='presentacion')return renderPresentation(); if(h==='docente')return renderTeacher(); if(h==='acerca')return renderAbout(); if(h==='historial')return renderHistory(); if(h==='recursos')return renderResources(); renderHome();}
function shell(title,html,cls=''){ $('#app').className='container '+cls; $('#app').innerHTML=`<section class="hero"><p class="eyebrow">${data.meta.tagline} · Versión ${data.meta.version} · Actualizado ${data.meta.updatedAt}</p><h1>${title}</h1></section>${html}`; $('#app').focus();}
function renderHome(){shell(data.meta.title,`<p class="lead">Curso creado y dirigido por <strong>${data.meta.authorFull}</strong>, para la formación de profesionales farmacéuticos en el uso crítico, seguro y aplicado de la inteligencia artificial.</p><div class="grid four">${data.levels.map(l=>`<article class="card"><span class="badge">${l.difficulty}</span><h2>${l.title}</h2><p>${l.hours} h estimadas</p><a class="btn" href="#catalogo">Ver módulos</a></article>`).join('')}</div><section class="card"><h2>Continuar donde lo dejé</h2><p>Progreso local guardado en este navegador. Módulos: ${state.doneModules.length}/${data.modules.length}. Casos: ${state.doneCases.length}/${data.cases.length}.</p><a class="btn" href="#${nextId()}">Continuar</a> <button class="btn secondary" data-action="certificate">Descargar informe</button> <button class="btn secondary" data-action="reset">Reiniciar</button></section>`)}
function nextId(){return data.modules.find(m=>!state.doneModules.includes(m.id))?.id||'casos'}
function renderCatalog(){shell('Catálogo modular completo',`<div class="grid two">${data.modules.map(m=>moduleCard(m)).join('')}</div>`)}
function moduleCard(m){return `<article class="card module"><span class="badge">${level(m.level)}</span><h2><a href="#${m.id}">${m.title}</a></h2><p>${m.estimatedMinutes} min · ${m.route} · ${m.updatedAt}</p><ul>${m.objectives.map(o=>`<li>${o}</li>`).join('')}</ul><a class="btn" href="#${m.id}">Abrir módulo</a> <button data-action="done-module" data-id="${m.id}">${state.doneModules.includes(m.id)?'Quitar completado':'Marcar completado'}</button></article>`}
function level(id){return data.levels.find(l=>l.id===id)?.title||id}
function renderModule(m){shell(m.title,`<article class="card"><p><strong>Nivel:</strong> ${level(m.level)} · <strong>Tiempo:</strong> ${m.estimatedMinutes} min · <strong>Autoría:</strong> ${m.author} · <strong>Revisión:</strong> ${m.updatedAt}</p><h2>Objetivos medibles</h2><ul>${m.objectives.map(x=>`<li>${x}</li>`).join('')}</ul><h2>Conocimientos previos</h2><ul>${m.prerequisites.map(x=>`<li>${x}</li>`).join('')}</ul>${m.sections.map(s=>`<details open><summary>${s.title}</summary><p>${s.body}</p></details>`).join('')}<h2>Checklist de aprendizaje</h2><ul>${m.checklist.map(x=>`<li>${x}</li>`).join('')}</ul>${assessment(m.assessment)}<h2>Recursos y fuentes</h2><ul>${m.references.map(r=>`<li><a href="${r.url}">${r.label}</a> (consulta ${r.checked})</li>`).join('')}</ul><nav class="module-nav">${m.previousModule?`<a class="btn secondary" href="#${m.previousModule}">Anterior</a>`:'<a class="btn secondary" href="#catalogo">Catálogo</a>'}<button class="btn" data-action="done-module" data-id="${m.id}">${state.doneModules.includes(m.id)?'Completado: desmarcar':'Marcar módulo completado'}</button>${m.nextModule?`<a class="btn" href="#${m.nextModule}">Siguiente</a>`:'<a class="btn" href="#casos">Ir a casos</a>'}<button class="btn secondary" data-action="set-deck" data-id="${m.id}">Presentar</button><a class="btn secondary" href="#docente">Modo docente</a></nav></article>`)}
function assessment(items){return `<h2>Microevaluación</h2>${items.map((it,i)=>`<fieldset><legend>${it.q}</legend>${it.options.map((o,j)=>`<label><input name="q${i}" type="radio" onchange="this.closest('fieldset').querySelector('.feedback').textContent='${it.feedback[j].replaceAll("'","’")}'"> ${o}</label>`).join('')}<p class="feedback">Seleccione una opción para ver retroalimentación.</p></fieldset>`).join('')}`}
function renderCases(){shell('Casos prácticos completos',`<div class="grid two">${data.cases.map(c=>`<article class="card"><span class="badge">Nivel ${c.level}</span><h2><a href="#${c.id}">${c.title}</a></h2><p>${c.professionalArea} · ${c.estimatedMinutes} min · competencia: ${c.competency}</p><p>${c.scenario}</p><a class="btn" href="#${c.id}">Resolver caso</a> <button data-action="done-case" data-id="${c.id}">${state.doneCases.includes(c.id)?'Completado':'Marcar completado'}</button></article>`).join('')}</div>`)}
function renderCase(c){shell(c.title,`<article class="card"><p><strong>Área:</strong> ${c.professionalArea} · <strong>Competencia:</strong> ${c.competency} · <strong>Autoría:</strong> ${c.author}</p>${['scenario','task','toolChoice','prompt','simulatedOutput','resolution'].map(k=>`<h2>${labelCase(k)}</h2><p>${c[k]}</p>`).join('')} ${list('Información disponible',c.availableInformation)}${list('Información ausente',c.missingInformation)}${list('Riesgos',c.risks)}${list('Flujo de trabajo',c.workflow)}${list('Errores deliberados',c.deliberateErrors)}${assessment(c.questions)}${list('Proceso de verificación',c.verificationProcess)}${list('Lecciones aprendidas',c.lessons)}${list('Rúbrica',c.rubric)}<nav class="module-nav"><a class="btn secondary" href="#casos">Volver a casos</a><button class="btn" data-action="done-case" data-id="${c.id}">${state.doneCases.includes(c.id)?'Caso completado: desmarcar':'Marcar caso completado'}</button><a class="btn secondary" href="#docente">Solución docente</a></nav></article>`)}
function labelCase(k){return {scenario:'Escenario ficticio',task:'Tarea del alumno',toolChoice:'Elección de herramienta',prompt:'Prompt inicial',simulatedOutput:'Resultado simulado de la IA',resolution:'Resolución razonada'}[k]}
function list(t,arr){return `<h2>${t}</h2><ul>${arr.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function deck(){if(state.deck==='all')return data.modules.flatMap(m=>m.presentationSlides.map(s=>({...s,source:m.title}))); const m=data.modules.find(x=>x.id===state.deck)||data.modules[0]; return m.presentationSlides.map(s=>({...s,source:m.title}));}
function renderPresentation(){const d=deck(); state.slide=Math.min(state.slide,d.length-1); const s=d[state.slide]; shell('Modo presentación',`<section class="slide card"><p class="eyebrow">${state.slide+1}/${d.length} · ${s.source}</p><h2>${s.title}</h2><h3>Objetivo</h3><p>${s.objective}</p><h3>Ideas clave</h3><ul>${s.keyIdeas.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Ejemplo</h3><p>${s.example}</p><h3>Pregunta para el grupo</h3><p>${s.question}</p><h3>Resumen</h3><p>${s.summary}</p><nav class="module-nav"><button class="btn secondary" data-action="slide-prev">Anterior</button><button class="btn" data-action="slide-next">Siguiente</button><button class="btn secondary" data-action="slides-reset">Reiniciar</button><button class="btn secondary" data-action="fullscreen">Pantalla completa</button><a class="btn secondary" href="#inicio">Salir</a></nav></section>`, 'presentation-mode')}
function moveSlide(n){const d=deck(); state.slide=Math.max(0,Math.min(d.length-1,state.slide+n)); save(); renderPresentation();}
function renderTeacher(){const m=data.modules[0]; shell('Modo docente',`<p class="lead">Guía diferenciada para impartir el curso. Las soluciones no se muestran al alumno por defecto.</p><div class="toolbar"><button class="btn" data-action="random-question">Pregunta aleatoria</button><button class="btn secondary" data-action="timer" data-minutes="10">Temporizador 10 min</button><button class="btn secondary" data-action="print">Imprimir hoja de sesión</button><button class="btn secondary" data-action="download-guide">Descargar guía docente</button><a class="btn" href="#presentacion">Lanzar presentación</a></div><div id="teacherTools"></div><div class="grid two">${data.modules.map(m=>teacherCard(m)).join('')}</div>`);}
function teacherCard(m){const g=m.teacherGuide; return `<article class="card teacher"><h2>${m.title}</h2><p><strong>Duración:</strong> ${g.duration}. <strong>Dificultad:</strong> ${g.difficulty}</p>${list('Objetivos docentes',g.objectives)}${list('Materiales',g.materials)}${list('Conceptos esenciales',g.essentialConcepts)}${list('Errores previsibles',g.predictableErrors)}${list('Preguntas de debate',g.debateQuestions)}<details><summary>Mostrar solución y respuesta esperada</summary><p>${g.expectedAnswer}</p>${list('Rúbrica',g.rubric)}</details><label>Notas privadas del docente<textarea id="notes-${m.id}">${state.teacherNotes[m.id]||''}</textarea></label><button data-action="notes-save" data-module="${m.id}">Guardar notas</button> <a class="btn secondary" href="#${m.id}">Ver módulo alumno</a></article>`}
function saveNotes(id){state.teacherNotes[id]=$(`#notes-${id}`).value;save();alert('Notas guardadas localmente.');}
function randomQuestion(){const m=data.modules[Math.floor(Math.random()*data.modules.length)]; $('#teacherTools').innerHTML=`<article class="card"><h2>Pregunta aleatoria</h2><p>${m.teacherGuide.debateQuestions[0]}</p><p><strong>Módulo:</strong> ${m.title}</p></article>`}
function startTimer(min){let end=Date.now()+min*60000; const box=$('#teacherTools'); const tick=()=>{let s=Math.max(0,Math.round((end-Date.now())/1000)); box.innerHTML=`<article class="card"><h2>Temporizador</h2><p>${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}</p></article>`; if(s>0)setTimeout(tick,1000)}; tick();}
function renderAbout(){shell('Acerca del curso',`<article class="card"><h2>Autor y dirección académica</h2><p>Curso creado y dirigido por <strong>${data.meta.authorFull}</strong>.</p><p>Desarrollo y actualización técnica asistidos mediante herramientas de inteligencia artificial, bajo dirección y revisión del autor.</p><h2>Propósito y público</h2><p>Formar profesionales farmacéuticos en uso crítico, seguro y aplicado de IA, con ruta específica para farmacia hospitalaria.</p><h2>Fechas y versión</h2><ul><li>Creación original verificada: enero de 2026, primer commit ${data.meta.createdAt}.</li><li>Rediseño integral: julio de 2026.</li><li>Última actualización: ${data.meta.updatedAt}.</li><li>Versión: ${data.meta.version}.</li></ul><h2>Metodología, alcance y limitaciones</h2><p>Módulos, casos, microevaluaciones, rúbricas, guía docente y progreso local. Uso exclusivamente formativo; no sustituye juicio profesional, fuentes oficiales ni políticas institucionales.</p><h2>Licencia y créditos</h2><p>CC BY-NC-SA 4.0 salvo indicación contraria. Autoría principal: ${data.meta.author}.</p><a class="btn" href="#historial">Ver historial de versiones</a></article>`)}
function renderHistory(){shell('Historial de versiones',`<table><thead><tr><th>Versión</th><th>Fecha</th><th>Cambios</th><th>Tipo</th><th>Responsable</th></tr></thead><tbody>${data.versionHistory.map(v=>`<tr><td>${v.version}</td><td>${v.date}</td><td>${v.changes}</td><td>${v.type}</td><td>${v.responsible}</td></tr>`).join('')}</tbody></table>`)}
function renderResources(){shell('Recursos, fuentes y glosario',`<div class="grid two"><article class="card"><h2>Fuentes verificadas</h2><ul>${data.references.map(r=>`<li><a href="${r.url}">${r.label}</a> · consulta ${r.checked}</li>`).join('')}</ul></article><article class="card"><h2>Glosario</h2>${Object.entries(data.glossary).map(([k,v])=>`<details><summary>${k}</summary><p>${v}</p></details>`).join('')}</article></div>`)}
function downloadCertificate(){const txt=`Informe de finalización no oficial\nCurso: ${data.meta.title}\nAutor: ${data.meta.author}\nVersión: ${data.meta.version}\nMódulos completados: ${state.doneModules.length}/${data.modules.length}\nCasos completados: ${state.doneCases.length}/${data.cases.length}\nFecha: ${new Date().toISOString()}\nUso formativo; no acreditación oficial salvo indicación expresa.`; blobDownload(txt,'informe-finalizacion-ia-farmacia.txt')}
function downloadGuide(){blobDownload(`Guía docente - ${data.meta.title}\nAutor: ${data.meta.author}\n\n`+data.modules.map(m=>`${m.title}\nObjetivos: ${m.teacherGuide.objectives.join('; ')}\nRúbrica: ${m.teacherGuide.rubric.join('; ')}`).join('\n\n'),'guia-docente-ia-farmacia.txt')}
function blobDownload(txt,name){let a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'})); a.download=name; a.click();}
init();
